set here [file join [absolute $srcdir] $subdir]
source $here/../../bdw.tcl
 
if { [info exists env(DISPLAY)] && $env(DISPLAY) != "" } {

# Check the typecheck command
bdw_run_compare_pass typecheck_test.tcl 
 
# Check the compile command
bdw_run_compare_pass compile_test.tcl 
 
# Check the link command
bdw_run_compare_pass link_test.tcl 
 
# Check the simulate command
bdw_run_compare_pass simulate_test.tcl 

}

