set here [file join [absolute $srcdir] $subdir]
source $here/../../bdw.tcl

if { [info exists env(DISPLAY)] && $env(DISPLAY) != "" } {

# Checks the Project menu functionality
bdw_run_compare_pass project_menu_test.tcl ""  "-e /modelsim/d"

# Checks the Build menu functionality
bdw_run_compare_pass build_menu_test.tcl

# Checks the Window menu functionality
bdw_run_compare_pass window_menu_test.tcl

}
 
