set here [file join [absolute $srcdir] $subdir]
source $here/../../bdw.tcl
 
if { [info exists env(DISPLAY)] && $env(DISPLAY) != "" } {

unset -nocomplain ::env(EDITOR)

# Check the typecheck command
bdw_run_compare_pass typecheck_via_bluesim_test.tcl 
 
# Check the typecheck command
bdw_run_compare_pass typecheck_via_verilog_test.tcl 
 
# Check the compile command
bdw_run_compare_pass compile_via_bluesim_test.tcl 
 
# Check the compile command
bdw_run_compare_pass compile_via_verilog_test.tcl 
 
# Check the link command
bdw_run_compare_pass link_via_bluesim_test.tcl 

# iverilog 10.1 has spurious warnings
set ere {}
if { $verilog_compiler == "iverilog" && $verilog_compiler_version == "10.1" } {
    append ere { -e {/inherits dimensions from var/d}}
}

# Check the link command
bdw_run_compare_pass link_via_verilog_test.tcl "" $ere
 
# Check the simulate command
bdw_run_compare_pass simulate_via_verilog_test.tcl "" $ere
 
# Check the simulate command
bdw_run_compare_pass simulate_via_bluesim_test.tcl

}

